"""empty message

Revision ID: 24265d9e4a05
Revises: afcb91399f58
Create Date: 2017-02-23 19:10:20.972509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24265d9e4a05'
down_revision = 'afcb91399f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_room',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_room')
    # ### end Alembic commands ###
