"""empty message

Revision ID: 4306ce5ab21c
Revises: 24265d9e4a05
Create Date: 2017-02-25 23:50:08.130367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4306ce5ab21c'
down_revision = '24265d9e4a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_selected_room', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'rooms', ['last_selected_room'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'last_selected_room')
    # ### end Alembic commands ###
