"""empty message

Revision ID: f41da34f6c0d
Revises: 
Create Date: 2017-05-07 13:05:23.871994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41da34f6c0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rooms', 'users', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'teacher_id')
    # ### end Alembic commands ###
