"""empty message

Revision ID: f537c19fb552
Revises: a32ddd4dffd8
Create Date: 2017-05-01 17:18:38.902485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f537c19fb552'
down_revision = 'a32ddd4dffd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('room_id', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'users', ['teacher_id'], ['id'])
    op.create_foreign_key(None, 'events', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'teacher_id')
    op.drop_column('events', 'room_id')
    # ### end Alembic commands ###
